### ISSUE TITLE
Unable to scan all devices

### ISSUE THREAD

**Issue by Dorbmon** [ujw0712/react-native-ble-phone-to-phone#2]
As I call 
`
advertiseStart("")
`
It paniced.
I need to scan all the nearby devices.

**Comment by ujw0712** [comment]
Hi,

Updated about that.
You can use `advertiseStart()` and `scanStart()`.

and, You can check the device data with the code below.
```
eventEmitter.addListener('foundDevice', (data) =>
  console.log('> foundDevice data : ', data)
);
```
